### ISSUE TITLE
[Vue warn]: Failed to resolve component: _self 

### ISSUE THREAD

**Issue by ShookLyngs** [megafetis/vue3-blocks-tree#2]
Using vite2 + vue3, this problem shows up when I use the component.
The problem seems to happen when blocks-node tried to repeat itself.

The child look like this in DOM tree:
```
<_self data="[object Object]" props="[object Object]" collapsable="false" labelwidth="auto"></_self>
```

**Comment by ChrisRAra** [comment]
Have you found a solution yet? I have the same issue

**Comment by megafetis** [comment]
I just updated to 0.5.0 version. Pleace check this bug again. Add to your code a `key` to node item. By default it is `id`

**Comment by megafetis** [comment]
try to update `"@vue/compiler-sfc": "^3.0.11"` and it should works

**Comment by ChrisRAra** [comment]
I still get the same issue after updating to v0.5.0 and vue 3.0.11 and vue/compiler-sfc 3.0.11.

I used the demo code as basis but still receive the same issue

**Comment by ChrisRAra** [comment]
Where would I need to add the key?

**Comment by megafetis** [comment]
@ChrisRAra, i understood that it works with `"vue": "3.0.5"` but with `"vue": "3.0.11"` shows warning

**Comment by ChrisRAra** [comment]
Ok cool so can I just downgrade vue to 3.0.5?

**Comment by megafetis** [comment]
Yes, it works for me. later I will try to fix this problem.

**Comment by ChrisRAra** [comment]
Thanks bro! Looking forward to the later fix as well but will do that for now

**Comment by megafetis** [comment]
@ChrisRAra the last version is 0.5.1. But problem not solved. `key` feature is for `:key` binding 
```vue
<blocks-tree :data="treeData" :horizontal="treeOrientation=='1'" :collapsable="true" :props="{label: 'label', expand: 'expand', children: 'children',  key:'some_id'}">
```

**Comment by ChrisRAra** [comment]
@megafetis ok cool so must I just update my .vue to that code?

**Comment by megafetis** [comment]
no, Not obligatory

**Comment by ChrisRAra** [comment]
@megafetis  thanks for updating it is working on vue 3.0.11

**Comment by Simone0705** [comment]
Bom dia, estou recebendo esse erro ao abrir a aplicacao
Uncaught TypeError: Object(...) is not a function
    at Module.fb15 (vue3-blocks-tree.common.js?5f52:1387)
    at __webpack_require__ (vue3-blocks-tree.common.js?5f52:21)
    at eval (vue3-blocks-tree.common.js?5f52:85)
    at eval (vue3-blocks-tree.common.js?5f52:88)
    at Object../node_modules/vue3-blocks-tree/dist/vue3-blocks-tree.common.js (chunk-vendors.js:1426)
    at __webpack_require__ (app.js:854)
    at fn (app.js:151)
    at eval (main.js:21)
    at Module../src/main.js (app.js:1076)
    at __webpack_require__ (app.js:854)
